image: binocarlos/cibase:v6

stages:
  - test

test_truffle:
  stage: test
  variables:
    APPNAME: lottery-$CI_JOB_ID
  before_script:
    - bash docker.sh build-truffle    
    - bash docker.sh ganache
  script:
    - bash docker.sh truffle test
  after_script:
    - bash docker.sh ganache-stop
    
